environments:
  dev:
    url: http://dev.com
    name: dev
  prod:
    url: http://prod.com
    name: prod
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /Projects/JavaEE/SpringBoot/log/
#  file: /Projects/JavaEE/SpringBoot/log/springBoot.log
